// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID int32          `json:"account_id"`
	Balance   pgtype.Numeric `json:"balance"`
}

type Attribute struct {
	AttributeID   int32  `json:"attribute_id"`
	AttributeName string `json:"attribute_name"`
	Value         string `json:"value"`
	ProductID     int32  `json:"product_id"`
}

type Cart struct {
	UserID    *int32 `json:"user_id"`
	ProductID *int32 `json:"product_id"`
	Quantity  *int32 `json:"quantity"`
}

type Category struct {
	CategoryID      int32            `json:"category_id"`
	Name            string           `json:"name"`
	Thumbnail       *string          `json:"thumbnail"`
	Description     *string          `json:"description"`
	SuperCategoryID *int32           `json:"super_category_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Manufacturer struct {
	ManufacturerID   int32            `json:"manufacturer_id"`
	ManufacturerName string           `json:"manufacturer_name"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type Order struct {
	OrderID   int32            `json:"order_id"`
	Total     pgtype.Numeric   `json:"total"`
	Status    *string          `json:"status"`
	OrderDate pgtype.Timestamp `json:"order_date"`
	UserID    *int32           `json:"user_id"`
}

type OrderDetail struct {
	OrderDetailID int32          `json:"order_detail_id"`
	ProductID     *int32         `json:"product_id"`
	Quantity      *int32         `json:"quantity"`
	Subtotal      pgtype.Numeric `json:"subtotal"`
	OrderID       *int32         `json:"order_id"`
}

type Product struct {
	ProductID      int32            `json:"product_id"`
	ProductName    string           `json:"product_name"`
	Price          pgtype.Numeric   `json:"price"`
	Stock          int32            `json:"stock"`
	Description    *string          `json:"description"`
	CategoryID     int32            `json:"category_id"`
	ManufacturerID *int32           `json:"manufacturer_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Discount       pgtype.Numeric   `json:"discount"`
	Type           *string          `json:"type"`
	Tag            *string          `json:"tag"`
}

type ProductImage struct {
	ProductID int32  `json:"product_id"`
	ImageUrl  string `json:"image_url"`
}

type Review struct {
	ReviewID  int32            `json:"review_id"`
	Content   string           `json:"content"`
	Rating    int32            `json:"rating"`
	PostedAt  pgtype.Timestamp `json:"posted_at"`
	ProductID int32            `json:"product_id"`
	UserID    int32            `json:"user_id"`
}

type Transaction struct {
	TransactionID int32            `json:"transaction_id"`
	AccountID     int32            `json:"account_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Status        *string          `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	OrderID       int32            `json:"order_id"`
}

type User struct {
	UserID        int32            `json:"user_id"`
	Username      *string          `json:"username"`
	Password      *string          `json:"password"`
	Permission    int32            `json:"permission"`
	LoginProvider *int32           `json:"login_provider"`
	ProviderID    *string          `json:"provider_id"`
	AccountID     *int32           `json:"account_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	Fullname      *string          `json:"fullname"`
	Phone         *string          `json:"phone"`
	Address       *string          `json:"address"`
	Avatar        *string          `json:"avatar"`
}
