// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]GetAllProductsRow, error)
	GetNewArrivalProducts(ctx context.Context) ([]GetNewArrivalProductsRow, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	GetUsers(ctx context.Context) (User, error)
}

var _ Querier = (*Queries)(nil)
